#server:
  #port: 8089

spring:
  application:
    name: feign-producer
  cloud:
    nacos:
      discovery:
        #server-addr: localhost:8848
        server-addr: 101.37.159.158:8848
        namespace: feign
