spring:
  application:
    name: dubbo-customer
  cloud:
    nacos:
      discovery:
        namespace: dubbo
        #server-addr: "127.0.0.1:8848"
        server-addr: 101.37.159.158:8848

dubbo:
  protocol:
    port: -1
    name: dubbo
  registry:
    address: nacos://101.37.159.158:8848
  # 消费者 订阅
  cloud:
    # 对所有的接口感兴趣: '*'
    # 指定服务感兴趣: 使用服务名
    # 对多个指定服务感兴趣: 使用服务名,用','隔开
    subscribed-services: dubbo-producer
#  订阅
